apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicycle
  labels:
    app: bicycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicycle
  template:
    metadata:
      labels:
        app: bicycle
    spec:
      containers:
        - name: bicycle
          image: username/bicycle:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5